B1_config:
  d_in: 4
  d_out: 2
  hidden_act_fn: Tanh
  hidden_layers:
  - 8
  - 4
  output_act_fn: Identity
B1_type: Det_Block
B2_config:
  d_in: 0
  d_out: 2
  hidden_act_fn: Tanh
  hidden_layers:
  - 8
  - 4
  output_act_fn: Identity
B2_type: Det_Block
B3_config:
  d_in: 3
  d_out: 1
  hidden_act_fn: Tanh
  hidden_layers:
  - 16
  - 32
  - 16
  - 8
  output_act_fn: Identity
B3_type: Prob_Block
dcat: null
dnum: 1
dout: 1
dsource: 4
loss_handler_config:
  LW_alg_classes:
  - Fixed_Weights
  - Two_Moment_Weighting
  LW_alg_configs:
  - num_loss_terms: 4
  - num_loss_terms: 1
  data_split_classes:
  - Split_by_Source
  - Split_by_Output_Dim
  data_split_configs:
  - num_sources: 4
  - num_outputs: 1
  loss_function_classes:
  - Output_NLL_loss
  loss_function_configs:
  - {}
  regularizer_classes:
  - Output_IS_loss
  regularizer_configs:
  - alpha: 0.05
    strength: 0.1
loss_handler_type: Hierarchical_Loss_Handler
optimizer_config:
  lr: 0.001
  weight_decay: 0.001
optimizer_type: Adam
qual_in: false
quant_in: true
